#!/usr/bin/env bash
#Bash script that configures an ubuntu machine to start an Ngnix server
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
