#!/usr/bin/env bash
# This file prints  "Holbertonschool" 10 times

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
	echo "Holberton School"
	echo "Hi";
    else
	echo "Holberton School"
    fi
    ((i++))
done
